# Complex test configuration for simulatorv3
# Client -> WLAN -> Slink -> Relay -> TrafficSrvr

# Node definitions
[[Node]]
id = 0
type = "ClientMBN"
coreside_out = 0  # Client sends via 0 to WLAN

#WLAN
[[Node]]
id = 1
type = "RouterBasic"
coreside_out = 1   # WLAN sends via 1 to Slink
edgeside_out = 4   # WLAN sends via 4 to Client
edgeside_in = 0    # WLAN recvs via 0 from Client

#Starlink
[[Node]]
id = 2
type = "RouterBasic"
coreside_out = 2   # Slink sends via 2 to Relay
edgeside_out = 5   # Slink sends via 5 to WLAN
edgeside_in = 1    # Slink recvs via 1 from WLAN

#VPN Relay
[[Node]]
id = 3
type = "RelayMBN"
coreside_out = 3   # sends via 3 to TrafficServer
edgeside_out = 6   # sends via 6 to Slink
edgeside_in = 2    # recvs via 2 from Slink

[[Node]]
id = 4
type = "TrafficServerBasic"
edgeside_out = 7   # sends via link 7 to Relay

# Link definitions
# Forward direction links (0->1->2->3->4)
# Link 0: from Client to WLAN
[[Link]]
id = 0
from = 0  # Client
to = 1    # WLAN
type = "FixedTput"
tput_bps = 100_000_000_000_000
prop_us = 2_000

# Link 1: from WLAN to Slink
[[Link]]
id = 1
from = 1  # WLAN
to = 2    # Starlink
type = "FixedTput"
tput_bps = 100_000_000_000_000
prop_us = 2_000

# Link 2: from Starlink to Relay
[[Link]]
id = 2
from = 2  # Starlink
to = 3    # Relay
type = "FixedTput"
tput_bps = 100_000_000_000_000
prop_us = 6_000

# Link 3: from Relay to TrafficServer
[[Link]]
id = 3
from = 3  # Relay
to = 4    # TrafficServer
type = "FixedTput"
tput_bps = 100_000_000_000_000
prop_us = 10_000

# Return direction links (4->3->2->1->0)
# Link 4: from WLAN to Client
[[Link]]
id = 4
from = 1  # WLAN
to = 0    # Client
type = "FixedTput"
tput_bps = 100_000_000_000_000
prop_us = 2_000

# Link 5: from Starlink to WLAN
[[Link]]
id = 5
from = 2  # Starlink
to = 1    # WLAN
type = "FixedTput"
tput_bps = 100_000_000_000_000
prop_us = 2_000

# Link 6: from Relay to Starlink
[[Link]]
id = 6
from = 3  # Relay
to = 2    # Starlink
type = "FixedTput"
tput_bps = 100_000_000_000_000
prop_us = 6_000

# Link 7: from TrafficServer to Relay
[[Link]]
id = 7
from = 4  # TrafficServer
to = 3    # Relay
type = "FixedTput"
tput_bps = 100_000_000_000_000
prop_us = 10_000

# Routing rules for WLAN node (id = 1)
[[Route]]
node_id = 1
forwarding_rules = [
    { in_link = 0, out_link = 1 },  # Cli -> Slink
    { in_link = 5, out_link = 4 }   # Slink -> Cli
]

# Routing rules for Starlink node (id = 2)
[[Route]]
node_id = 2
forwarding_rules = [
    { in_link = 1, out_link = 2 },  # WLAN -> Relay
    { in_link = 6, out_link = 5 }   # Relay -> WLAN
]

# Routing rules for Relay node (id = 3)
[[Route]]
node_id = 3
forwarding_rules = [
    { in_link = 2, out_link = 3 },  # Slink -> TSrv
    { in_link = 7, out_link = 6 }   # TSrv -> link
]